Merge scripts/test with other projects

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -1,38 +1,44 @@
 #!/usr/bin/env bash
 
-check_cmd() {
+check-cmd() {
     CMD=$1
     which $CMD > /dev/null
     if [[ $? == 1 ]]; then
-        help_cmd $@
+        help-cmd $@
     fi
     test -x $(which $CMD)
     if [[ $? == 1 ]]; then
-        help_cmd $@
+        help-cmd $@
     fi
 }
 
-help_cmd() {
+help-cmd() {
     echo "$1 not found"
     shift
     echo "Execute the following to install: $*"
     exit 1
 }
 
-check_cmd goimports "go get golang.org/x/tools/cmd/goimports"
-check_cmd ginkgo    "go get github.com/onsi/ginkgo/ginkgo"
+check-cmd goimports "go get golang.org/x/tools/cmd/goimports"
+check-cmd ginkgo    "go get github.com/onsi/ginkgo/ginkgo"
 
 set -e
+
+error-trap() {
+    echo -e "\033[1m\033[41m Failed!                                                                        \033[0m"
+}
+
+trap 'error-trap' ERR
 
 cd $(dirname $0)/..
 
 goimports -w .
 
-echo -e "\033[1m\033[42mUnit tests...                                                                   \033[0m"
-ginkgo -r -keepGoing -race -skipPackage integration_tests $@
+echo -e "\033[1m\033[42m Unit tests...                                                                  \033[0m"
+ginkgo -r --skipPackage integration_tests --keepGoing --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress $@
 
-echo -e "\033[1m\033[42mIntegration tests...                                                            \033[0m"
+echo -e "\033[1m\033[42m Integration tests...                                                           \033[0m"
 cd integration_tests
-ginkgo -r -keepGoing -race -skipPackage integration_tests $@
+ginkgo -r --keepGoing --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress $@
 
-echo -e "\033[1m\033[42mCompleted successfully.                                                         \033[0m"
+echo -e "\033[1m\033[42m Completed successfully.                                                        \033[0m"
