Make netspel go get-able

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -1,8 +1,30 @@
 #!/usr/bin/env bash
 
+check_cmd() {
+    CMD=$1
+    which $CMD > /dev/null
+    if [[ $? == 1 ]]; then
+        help_cmd $@
+    fi
+    test -x $(which $CMD)
+    if [[ $? == 1 ]]; then
+        help_cmd $@
+    fi
+}
+
+help_cmd() {
+    echo "$1 not found"
+    shift
+    echo "Execute the following to install: $*"
+    exit 1
+}
+
+check_cmd goimports "go get golang.org/x/tools/cmd/goimports"
+check_cmd ginkgo    "go get github.com/onsi/ginkgo/ginkgo"
+
 set -e
 
-cd $(dirname $0)/../src/netspel
+cd $(dirname $0)/..
 
 goimports -w .
 
